#!/bin/bash

# Stalker WM Portal road warrior installer for Debian, Ubuntu

# This script will work on Debian, Ubuntu and probably other distros
# of the same families, although no support is offered for them. It isn't
# bulletproof but it will probably work if you simply want to setup a Stalker WM Portal on
# your Debian/Ubuntu box. It has been designed to be as unobtrusive and
# universal as possible.

# This is a free shell script under GNU GPL version 3.0 or above
# Copyright (C) 2017 LinuxHelps project.
# Feedback/comment/suggestions : https://linuxhelps.net/
# Author Ivan Bachvarov a.k.a SlaSerX


# Color schema

red='\033[01;31m'
blue='\033[01;34m'
green='\033[01;32m'
norm='\033[00m'

# Temporary colors
RED="$(tput setaf 1)"
YELLOW="$(tput setaf 3)"
CYAN="$(tput setaf 6)"
NORMAL="$(tput sgr0)"

# smallLoader colors

CSI="\033["
CEND="${CSI}0m"
CRED="${CSI}1;31m"
CGREEN="${CSI}1;32m"
CYELLOW="${CSI}1;33m"
CPURPLE="${CSI}1;35m"
CCYAN="${CSI}1;36m"
CBROWN="${CSI}0;33m"

# smallLoader

smallLoader() {
    echo ""
    echo ""
    echo -ne '[ + + +             ] 3s \r'
    sleep 1
    echo -ne '[ + + + + + +       ] 2s \r'
    sleep 1
    echo -ne '[ + + + + + + + + + ] 1s \r'
    sleep 1
    echo -ne '[ + + + + + + + + + ] Press [Enter] to continue... \r'
    echo -ne '\n'

    read -r
}



VER="5.2.0"
PRODUCT="Stalker Portal"
WEB="http://`ip route get 8.8.8.8 | awk '{print $NF; exit}'`/stalker_portal"
WAN="`wget -q -O - http://icanhazip.com/ | tail`"
LOCAL="`ip route get 8.8.8.8 | awk '{print $NF; exit}'`"

supported="    Debian 7, 8 on i386 and amd64
    Ubuntu 14.04 LTS "

skipyesno=0

# Ask a yes or no question
# if $skipyesno is 1, always Y
# if NONINTERACTIVE environment variable is 1, always Y
yesno () {
  # XXX skipyesno is a global set in the calling script
  # shellcheck disable=SC2154
  if [ "$skipyesno" = "1" ]; then
    return 0
  fi
  if [ "$NONINTERACTIVE" = "1" ]; then
    return 0
  fi
  while read -r line; do
    case $line in
      y|Y|Yes|YES|yes|yES|yEs|YeS|yeS) return 0
      ;;
      n|N|No|NO|no|nO) return 1
      ;;
      *)
      printf "\n${YELLOW}Please enter ${CYAN}[y]${YELLOW} or ${CYAN}[n]${YELLOW}:${NORMAL} "
      ;;
    esac
  done
}

install_msg() {
cat <<EOF

  Welcome to the ${RED}$PRODUCT${NORMAL} installer, version ${RED}$VER${NORMAL}

  This script must be run on a freshly installed supported OS. It does not
  perform updates or upgrades (use your system package manager).

  The systems currently supported by install.sh are:

EOF
echo "${CYAN}$supported${NORMAL}"
cat <<EOF

  If your OS/version/arch is not listed, installation ${RED}will fail${NORMAL}. More
  details about the systems supported by the script can be found here:

    ${UNDERLINE}${CYAN}https://github.com/SlaSerX/stalker/blob/master/docs/os-suport${NORMAL}


EOF

  printf " Continue? (y/n) "
  if ! yesno; then
    exit
  fi
}

if [ "$skipyesno" -ne 1 ] && [ -z "$setup_only" ]; then
  install_msg
fi


# 

pass="st@lk3r"
source="http://linuxhelps.net/configs"

#Install Necessary services & packets
sudo apt-get install -y -u apache2 nginx wget nano curl nginx-extras unzip memcached php5 php5-mysql php-pear nodejs upstart && sudo pear channel-discover pear.phing.info && sudo pear install -Z phing/phing 
sleep 1
pear channel-discover pear.phing.info
pear install phing/phing
sleep 1

# Set the Server Timezone to CST
echo "Europe/Sofia" > /etc/timezone
dpkg-reconfigure -f noninteractive tzdata

# Install MySQL Server in a Non-Interactive mode. Default root password will be "st@lk3r"
echo "mysql-server mysql-server/root_password password $pass" | sudo debconf-set-selections
echo "mysql-server mysql-server/root_password_again password $pass" | sudo debconf-set-selections

apt-get install -y mysql-server > /dev/null

sed -i 's/127\.0\.0\.1/0\.0\.0\.0/g' /etc/mysql/my.cnf
mysql -uroot -p$pass -e 'USE mysql; UPDATE `user` SET `Host`="%" WHERE `User`="root" AND `Host`="localhost"; DELETE FROM `user` WHERE `Host` != "%" AND `User`="root"; FLUSH PRIVILEGES;'
service mysql restart

cd /var/www/html/
wget http://lab.itbox.bg/software/tv/stalker_portal-5.2.0.zip
unzip stalker_portal-5.2.0.zip
mv infomirgroup-stalker_portal-9e60f9025ab6 stalker_portal
rm -rf *.zip

mysql -uroot -p$pass -e "create database stalker_db"
mysql -uroot -p$pass -e "GRANT ALL PRIVILEGES ON stalker_db.* TO stalker@localhost IDENTIFIED BY '1' WITH GRANT OPTION;"
echo "max_allowed_packet = 32M" >> /etc/mysql/my.cnf
echo "short_open_tag = On" >> /etc/php5/apache2/php.ini
a2enmod rewrite
apt-get purge libapache2-mod-php5filter > /dev/null

cd /etc/apache2/sites-enabled/
rm -rf *
wget $source/000-default.conf
cd /etc/apache2/
rm -rf ports.conf
wget $source/ports.conf
cd /etc/nginx/sites-available/
rm -rf default
wget $source/default
/etc/init.d/apache2 restart
/etc/init.d/nginx restart
/etc/init.d/apache2 restart
/etc/init.d/nginx restart

cd /var/www/html/stalker_portal/deploy
sudo phing
sleep 1
smallLoader

echo ""
echo -e "${CCYAN}-----------------------------------------------------------------------${CEND}"
echo ""
echo -e "${CCYAN}[ Install Complete Default username is: ${CRED}admin${CEND} ${CCYAN}Default password is: ${CRED}1${CEND} ${CCYAN}: ]${CEND}"
echo ""
echo -e "IP WAN       : ${CGREEN}${WAN}${CEND}"
echo -e "Local IP     : ${CGREEN}${LOCAL}${CEND}"
echo -e "MySQL Pass   : ${CGREEN}${pass}${CEND}"
echo -e "WEB          : ${CGREEN}${WEB}${CEND}"
echo ""
echo -e "${CCYAN}-----------------------------------------------------------------------${CEND}"
echo ""


